#!/usr/bin/env bash

# Nako: Ports-like system for Debian
# License: GNU General Public License, version 3 or later
# Copyright (c) 2023 Radio New Japan Broadcasting Club <njb-fm@via.tokyo.jp>
# Copyright (c) 2023 by Hayate Nakamura

NAKO_VERSION="1.0.0-Alpha1"
srcdir=$(pwd)/src
pkgdir=$(pwd)/pkg

read_pkgbuild() {
  MAINTAINER=$(grep -oP '(?<=# Maintainer:).+' PKGBUILD)
  PKGNAME=$(grep -oP '(?<=pkgname=).+' PKGBUILD)
  PKGVER=$(grep -oP '(?<=pkgver=).+' PKGBUILD)
  PKGREL=$(grep -oP '(?<=pkgrel=).+' PKGBUILD)
  PKGDESC=$(grep -oP '(?<=pkgdesc=).+' PKGBUILD)
  ARCH=$(grep -oP '(?<=arch=).+' PKGBUILD)
  URL=$(grep -oP '(?<=url=).+' PKGBUILD)

  if [[ $(grep epoch PKGBUILD|grep -oP '.+(?==)') == "epoch" ]]; then
    EPOCH=$(grep -oP '(?<=epoch=).+' PKGBUILD)
    PKGVERFULL="${EPOCH}:${PKGVER}-${PKGREL}"
  else
    EPOCHON=0
    PKGVERFULL="${PKGVER}-${PKGREL}"
  fi

  if [ ${ARCH} == "all" ] || [ ${ARCH} == "('all')" ] || [ ${ARCH} == '("all")' ]; then
    ARCH=all
  elif [ ${ARCH} == "amd64" ] || [ ${ARCH} == "('amd64')" ] || [ ${ARCH} == '("amd64")' ]; then
    ARCH=amd64
  fi

  if [[ $(grep section PKGBUILD|grep -oP '.+(?==)') == "section" ]]; then
    SECTION=$(grep -oP '(?<=section=).+' PKGBUILD)
  fi

  if [[ $(grep priority PKGBUILD|grep -oP '.+(?==)') == "section" ]]; then
    PRIORITY=$(grep -oP '(?<=section=).+' PKGBUILD)
  fi

  # Dependencies
  #DEPS=

  #BUILDDEPS=
}

package() {
mkdir ${srcdir} ${pkgdir}

mkdir ${pkgdir}/DEBIAN
echo "Package: ${PKGNAME}" > ${pkgdir}/DEBIAN/control
echo "Version: ${PKGVERFULL}" >> ${pkgdir}/DEBIAN/control
echo "Architecture: ${ARCH}" >> ${pkgdir}/DEBIAN/control
echo "Maintainer: ${MAINTAINER}" >> ${pkgdir}/DEBIAN/control
echo "Description: ${PKGDESC}" >> ${pkgdir}/DEBIAN/control


  echo ${PKGNAME}_${PKGVERFULL}_${ARCH}.deb 
  # dpkg-deb -Z${compress} -b pkg ${PKGNAME}_${EPOCH}:${PKGVER}-${PKGREL}_${ARCH}.deb
}

read_pkgbuild
package

