#!/usr/bin/env bash

# Nako - Bash-based AUR Helper
# Copyright (c) 2023, Radio New Japan Broadcasting Club All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
# * Redistributions of source code must retain the above copyright notice, 
#  this list of conditions and the following disclaimer.
# * Redistributions in binary form must reproduce the above copyright notice, 
#   this list of conditions and the following disclaimer in the documentation 
#   and/or other materials provided with the distribution.
# * Neither the name of the copyright holder nor the names of its contributors 
#   may be used to endorse or promote products derived from this software 
#   without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS “AS IS” AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY
# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

nako_version="0.1"
nako_name="Nako"
nako_cmd="nako"
nako_path="$(dirname $(realpath ${0}))/$(basename ${0})"

pacman_cmd="/usr/bin/pacman"
pacman_cfg="/etc/pacman.conf"
pacman_args=()

makepkg_cmd="/usr/bin/makepkg"
makepkg_cfg="/etc/makepkg"
makepkg_args=()

git_cmd="/usr/bin/git"
git_args=()

gpg_cmd="/usr/bin/gpg"
gpg_args=()

sudo_cmd="/usr/bin/sudo"
sudo_args=()

curl_cmd="/usr/bin/curl"
curl_args=()

aur_url="https://aur.archlinux.org/"

